### ISSUE TITLE
Contacts and Accounting Users

### ISSUE THREAD

**Issue by ChristoforosKotsios** [wp-erp/wp-erp#1063]
Hi guys! 

There is one problem with the relation between Contacts and Accounting Users. 

As you know, there is a choice in Settings of Accounting Module that allows the sync between them. Although it needs to be more customizable, because the only thing that it does is to sync **every** contact with Customers. This is a problem because a contact may be a vendor or only a contact. 

For this reason, I suggest refreshing the code in order to make sync according to life-stages or better according to Contact Groups. 

Finally, I think that it is not very helpful to not allow the same User to be both Customer and Vendor, because the wp_erp_people table in DB allows more that one records with the same user ID.

**Comment by thebengalboy** [comment]
Hello @ChristoforosKotsios 

No, we are not considering customers, and vendors are the same person. They are different both theoretically and technically.

Synchronization between contacts(CRM) and customers(Accounting) doesn't depend on the life stages or group. We are not considering this for now.

I'm closing the issue here as none of the mentioned is an issue.

Thanks
