### ISSUE TITLE
Issue with CRM and creating Contacts

### ISSUE THREAD

**Issue by Truative** [wp-erp/wp-erp#346]
Hi,

I am having an issue with The CRM module specifically. My first issue is the contacts section. When i go to create a new contact, the drop downs for the state, country, life stage and ect for all drop downs show up as a blue link and i cannot click it, thus inhibiting me from being able to create new contacts. Thus on the schedules page i cannot create a new schedule because the drop downs are not working there either as well as when i try to exit out of a new schedule it doesnt exit out and in the URL i just see a '#' show up after i clock the X. 

EDIT: I have found the issue with the problem. A plugin called "Woocommerce payment status" is inhibiting me from all those options. Is there any way we can fix this?

**Comment by codeshah** [comment]
Hello @Truative,

Previously we found the similar problem with WooCommerce based plugins like **WooCoomerce Point of Sale** and **WooCommerce Payment Status** because they were using an older version of **select2.js**.

If possible please check if the plugin you have mentioned has any select2 file attached to it and if it is up to date. If you find any outdated version, you can update yourself or contact the plugin author.

If you're unable to check, then you can send the plugin to support at wperp dot com. We will check and let you know the diagnosis result.

Thank you for using WP ERP :)

**Comment by Truative** [comment]
Hi Sekander,
Thank you for getting back to me so quickly.

I am also having an issue with the auto import into the Contacts. There are
a few new users and still they have no imported into the contacts of CRM.
How can we fix this?

Thank you!

Aaron




Best,

Aaron Attarzadeh | Unknwn Studios Development Director | (310) 804-4163

**Comment by Truative** [comment]
Correction: It works.

Thank you!




Best,

Aaron Attarzadeh | Unknwn Studios Development Director | (310) 804-4163

**Comment by Truative** [comment]
Another Issue:

When you change a customer to lead, it does not populate the "Lead"
section. See pictures for reference.




Best,

Aaron Attarzadeh | Unknwn Studios Development Director | (310) 804-4163

**Comment by codeshah** [comment]
@Truative as you are replying via email the attachments are not being posted here on Github. Please send those to support at wperp dot com or here

**Comment by ediamin** [comment]
@Truative If you still having your new issue, please open a new issue thread. Since your original issue has been resolved, I'm closing this issue.
