### ISSUE TITLE
Employees List Not Showing Up

### ISSUE THREAD

**Issue by MauriceMok** [wp-erp/wp-erp#556]
Hi would like to ask if there are similar issues where after updating the worpress site and also the ERP app, when click on the employees button, the employees page is actually blank. Can some one please assist in this issue?

**Comment by shawon786** [comment]
@MauriceMok,
Just checked the latest version of WP ERP & WordPress together.  But there was no such issue.
See the result- https://drive.google.com/file/d/10jmGzt2z49E4CwzviDJjukqOg7u7gap8/view

**Possible Solution:**
You may be facing this due to a plugin conflict. Please check for plugin conflicts or try WP ERP  in a fresh installation of WordPress.

Thanks :)

**Comment by MauriceMok** [comment]
Ok, let me try to see reinstall the whole thing afresh again.

**Comment by MauriceMok** [comment]
Hi Shawon786, I had followed your instructions and did a fresh copy of installation for wordpress and also the WP ERP but still the same. Can you help me to see what is the issue is all about?

**Comment by sultann** [comment]
@MauriceMok are you still experiencing the issue with the latest version of WP ERP v1.3.1?
