### ISSUE TITLE
Feature - Create Company from Contact Form

### ISSUE THREAD

**Issue by shawon786** [wp-erp/wp-erp#645]
It would be great to have a contact form that creates a company instead of a contact.

**Comment by thebengalboy** [comment]
Hello @shawon786 

Thanks for the good feature request but a company is not a person- who can contact over a contact form.

If someone fills a form to contact, means, he/she is a person and that suits the contact as a lead.

Unfortunately, we are not considering this right now and closing the issue here.

Thanks
