### ISSUE TITLE
CRM module: Company / Contact links don't get trashed

### ISSUE THREAD

**Issue by thomasdiesenreiter** [wp-erp/wp-erp#712]
When I delete a contact, linked companies still show the contact. When i permadelete the contact, there is then an empty link in the company profile. Also applies to the other way around.
Solution: Delete link between contacts / companys, if they get deleted themselves.

**Comment by thomasdiesenreiter** [comment]
He, while where are at it, what about this serious bug? Anybody cared to look into it in the last 8 Months?

**Comment by thebengalboy** [comment]
Hello @thomasdiesenreiter 

This was not an issue actually, rather kind of enhancement. A contact is not deletable that is linked with a company. So, it was not being deleted. However, we have added a warning while deleting a contact. Something like this:
`You can't delete this contact as this contact has a relation with the company X. Please make sure this contract is not assigned to any company before deleting.`  Fixed with the commit #830 

We generally take quick actions when we get a report but we somehow overlooked this. My apologies.

Thanks
