### ISSUE TITLE
Dual role CRM agent and Accounting Manager

### ISSUE THREAD

**Issue by tjlabais** [wp-erp/wp-erp#835]
If a user has dual role, a CRM agent at the same time an Accounting Manager, Customer List disappears in Accounting Customer List (auto copy enabled in settings) 

The number of customers can be seen but no data is shown.

After removing CRM agent role, the Customer List under accounting shows, but the user can no longer access CRM. I have to grant CRM Manager role for the user to have access to both CRM and Accounting.

Also, Accounting has no user level restrictions which means any user assigned under accounting is assumed to be a manager even if they are just the staff in the company.

**Comment by thebengalboy** [comment]
Hello @tjlabais 

This is not a problem actually, rather an intentional behavior. Let me explain:

- A CRM/Accounting manager can see all of the contacts/customers, they have full access.
- An Agent can see/access the contacts that he/she owns only.

So, when you provide the agent role to a user/manager, he could not see the other peoples' contacts/customers. A person can not be a manager and an agent at a time.

Thanks

**Comment by tjlabais** [comment]
@thebengalboy 

Thank you for the clarification. This behavior also goes back to the missing agent level for accounting; thus, assigning both agent/manager rights at the same time for 2 different modules.

I never wanted the agent to have full access for accounting, but only to fill up invoice from accounting module.

**Comment by thebengalboy** [comment]
Hello @tjlabais 

Accounting doesn't have any agent role or any custom role to provide specific access. Only Accounting managers can have access to Accounting.

As this is not an issue, I'm closing it here. If you need any help further, feel free to get in touch with our support team. You can email them to support@wperp.com

Thanks
