### ISSUE TITLE
Accounting: Problem fetching the customer address into invoice

### ISSUE THREAD

**Issue by thebengalboy** [wp-erp/wp-erp#947]
**Description:**
The invoice doesn't fetch and shows the customer address postal code.

**How to Reproduce**
Create a customer, then create an invoice for them to check his address pulled over it.

**Expected behavior**
Zip or Postal code should be added on the invoice

**Screenshot**:  https://prnt.sc/ql461v

Additionally, it shows the short name of the country & state name, which is wrong. It needs to show the full country, state name. Reference: https://prnt.sc/ql46cx

**Comment by probizsoftwarets** [comment]
I am the user that discovered the issue. Please let me know if I can test for you. Thanks Tim

**Comment by thebengalboy** [comment]
Also, it should not show the street_1, street_2 in the database. Actually, we need to fetch the saved values only, not the complete data with the table name.

Reference: https://prnt.sc/qln41g

**Comment by probizsoftwarets** [comment]
Another bug has been introduced. When attempting to update the info I cannot choose a country and state.... see attached. 
<img width="918" alt="Screen Shot 2020-01-10 at 7 46 19 AM" src="https://user-images.githubusercontent.com/59696005/72154050-8f84e000-337d-11ea-82fc-d026cdaf43e8.png">

**Comment by probizsoftwarets** [comment]
Are you actually fixing this stuff? I see your closing the ticket but I am not seeing any fixes at all. If you actually test this you will see that the Zip does not show up on invoices and now you cannot even choose the state… 

Thanks Tim

**Comment by probizsoftwarets** [comment]
See attached. The State is missing and it defaults to North Cape and should not

Also if you look at invoices there is no zip showing on the invoice

**Comment by probizsoftwarets** [comment]
I am running mac btw but I also tested on Firefox

**Comment by thebengalboy** [comment]
Hello @probizsoftwarets 

[This](https://prnt.sc/qn2bju) means the issue has been fixed with the commit #e68f769

Thanks

**Comment by probizsoftwarets** [comment]
The screenshots I sent this am was from this morning so I dont see it as being fixed >Thanks, Tim

**Comment by probizsoftwarets** [comment]
In my testing they have not been resolved. Have u submitted the updates?

Probiz Software

**Comment by thebengalboy** [comment]
You need to wait for the next version release to get this update, or you can use the development version from the GitHub repository.

**Comment by probizsoftwarets** [comment]
Hi Team,
I love the support that you guys give and would love to discuss our needs further. We ran a software company for years and sold the platform but we have a new business and looking at your platform it seems that your system would work well. We are quite good at finding bugs and could help there because our entire team has done development work for years. I have a few questions:

1 - What are recommended modules we would need to run our entire company from the portal? 
2 - What are the most used modules including those where each module communicates with the others on things like support tickets, chat etc….

3 - We found what appears to be another bug. Here is how we can replicate it: on the Import tab of of the WP ERP tab we can set up a csv file and import it but when we import the file after configuring it to be as required the file says it imports it but we cannot find the imported contacts…….. We are importing a CSV file by the way….

Thanks and we look forward to your reply.  Thanks, Tim

**Comment by thebengalboy** [comment]
Hello @probizsoftwarets 

I'd request you to contact our support for the pre-sales queries. GitHub issues are meant to discuss particular issues on WPERP actually.

You can catch our sales team directly here-> https://wperp.com/contact/

Thanks

**Comment by probizsoftwarets** [comment]
I am aware of that. See below;
> 
>  - We found what appears to be another bug. Here is how we can replicate it: on the Import tab of of the WP ERP tab we can set up a csv file and import it but when we import the file after configuring it to be as required the file says it imports it but we cannot find the imported contacts…….. We are importing a CSV file by the way….
> 
>
